# Generated by Django 4.2.3 on 2023-08-11 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='nam',
        ),
    ]
